version: '3'

services:
  vue_ussd_decoder:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vue-ussd-decoder
    restart: unless-stopped
    networks:
      - local
    ports:
      - "5173:5173"

networks:
  local:
    external: true